// SQL column projections for the invoice read queries, extracted so the
// repository file stays under the source-size guardrail. Pure column lists with
// camelCase aliases that mirror InvoiceRow / InvoiceLineItemRow.

export const INVOICE_COLUMNS = `
  id,
  job_id as "jobId",
  invoice_kind as "invoiceKind",
  status,
  tax_rate_basis_points as "taxRateBasisPoints",
  discount_kind as "discountKind",
  discount_basis_points as "discountBasisPoints",
  discount_amount as "discountAmount",
  subtotal_amount as "subtotalAmount",
  discount_amount_applied as "discountAmountApplied",
  taxable_base_amount as "taxableBaseAmount",
  tax_amount as "taxAmount",
  total_amount as "totalAmount",
  total_cost_amount as "totalCostAmount",
  profit_amount as "profitAmount",
  margin_basis_points as "marginBasisPoints",
  cost_complete as "costComplete",
  created_at as "createdAt",
  updated_at as "updatedAt",
  version,
  posted_at as "postedAt",
  posted_by_name as "postedByName",
  bill_to_customer_id as "billToCustomerId",
  bill_to_customer_name as "billToCustomerName",
  bill_to_account_type as "billToAccountType",
  bill_to_address_line1 as "billToAddressLine1",
  bill_to_city as "billToCity",
  bill_to_state as "billToState",
  bill_to_postal_code as "billToPostalCode",
  service_location_id as "serviceLocationId",
  service_location_name as "serviceLocationName",
  service_location_address_line1 as "serviceLocationAddressLine1",
  service_location_city as "serviceLocationCity",
  service_location_state as "serviceLocationState",
  service_location_postal_code as "serviceLocationPostalCode",
  job_number as "jobNumber",
  work_order_number as "workOrderNumber",
  adjusts_invoice_id as "adjustsInvoiceId",
  invoice_number as "invoiceNumber"
`;

export const INVOICE_LINE_COLUMNS = `
  id,
  invoice_id as "invoiceId",
  line_position as "position",
  kind,
  description,
  quantity,
  unit_of_measure as "unitOfMeasure",
  unit_price as "unitPrice",
  unit_cost as "unitCost",
  taxable,
  part_number as "partNumber",
  inventory_source_label as "inventorySourceLabel",
  line_subtotal_amount as "lineSubtotal",
  line_cost_amount as "lineCost",
  source_kind as "sourceKind",
  source_sync_state as "sourceSyncState",
  created_at as "createdAt",
  updated_at as "updatedAt"
`;
